demo-dev/src/Entity/Citoyen.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * Citoyen
 *
 * @ORM\Table(name="citoyen", indexes={@ORM\Index(name="IDADRESSE", columns={"IDADRESSE"})})
 * @ORM\Entity(repositoryClass="App\Repository\CitoyenRepository")
 */
class Citoyen implements UserInterface
{
    /**
     * @var int
     *
     * @ORM\Column(name="IDCITOYEN", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idcitoyen;

    /**
     * @var string|null
     *
     * @ORM\Column(name="NOMCITOYEN", type="string", length=256, nullable=true)
     */
    private $nomcitoyen;

    /**
     * @var string|null
     *
     * @ORM\Column(name="PRENOMCITOYEN", type="string", length=256, nullable=true)
     */
    private $prenomcitoyen;

    /**
     * @var string
     *
     * @ORM\Column(name="COURIELCITOYEN", type="string", length=512, nullable=false)
     */
    private $courielcitoyen;

    /**
     * @var string|null
     *
     * @ORM\Column(name="TELCITOYEN", type="string", length=256, nullable=true)
     */
    private $telcitoyen;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="NAISSANCECITOYEN", type="date", nullable=true)
     */
    private $naissancecitoyen;

    /**
     * @var string|null
     *
     * @ORM\Column(name="MDPCITOYEN", type="string", length=256, nullable=true)
     */
    private $mdpcitoyen;

    public $confirm_mdp;

    /**
     * @var bool|null
     *
     * @ORM\Column(name="VALIDATIONCITOYEN", type="boolean", nullable=true)
     */
    private $validationcitoyen;

    /**
     * @var string|null
     *
     * @ORM\Column(name="CLEVALIDATIONCITOYEN", type="string", length=256, nullable=true)
     */
    private $clevalidationcitoyen;

    /**
     * @var int|null
     *
     * @ORM\Column(name="IDADRESSE", type="integer", nullable=true)
     */
    private $idadresse;

    public function getIdcitoyen(): ?int
    {
        return $this->idcitoyen;
    }

    public function getNomcitoyen(): ?string
    {
        return $this->nomcitoyen;
    }

    public function setNomcitoyen(?string $nomcitoyen): self
    {
        $this->nomcitoyen = $nomcitoyen;

        return $this;
    }

    public function getPrenomcitoyen(): ?string
    {
        return $this->prenomcitoyen;
    }

    public function setPrenomcitoyen(?string $prenomcitoyen): self
    {
        $this->prenomcitoyen = $prenomcitoyen;

        return $this;
    }

    public function getCourielcitoyen(): ?string
    {
        return $this->courielcitoyen;
    }

    public function setCourielcitoyen(string $courielcitoyen): self
    {
        $this->courielcitoyen = $courielcitoyen;

        return $this;
    }

    public function getTelcitoyen(): ?string
    {
        return $this->telcitoyen;
    }

    public function setTelcitoyen(?string $telcitoyen): self
    {
        $this->telcitoyen = $telcitoyen;

        return $this;
    }

    public function getNaissancecitoyen(): ?\DateTimeInterface
    {
        return $this->naissancecitoyen;
    }

    public function setNaissancecitoyen(?\DateTimeInterface $naissancecitoyen): self
    {
        $this->naissancecitoyen = $naissancecitoyen;

        return $this;
    }

    public function getMdpcitoyen(): ?string
    {
        return $this->mdpcitoyen;
    }

    public function setMdpcitoyen(?string $mdpcitoyen): self
    {
        $this->mdpcitoyen = $mdpcitoyen;

        return $this;
    }

    public function getValidationcitoyen(): ?bool
    {
        return $this->validationcitoyen;
    }

    public function setValidationcitoyen(?bool $validationcitoyen): self
    {
        $this->validationcitoyen = $validationcitoyen;

        return $this;
    }

    public function getClevalidationcitoyen(): ?string
    {
        return $this->clevalidationcitoyen;
    }

    public function setClevalidationcitoyen(?string $clevalidationcitoyen): self
    {
        $this->clevalidationcitoyen = $clevalidationcitoyen;

        return $this;
    }

    public function getIdadresse(): ?int
    {
        return $this->idadresse;
    }

    public function setIdadresse(?int $idadresse): self
    {
        $this->idadresse = $idadresse;

        return $this;
    }

    public function getSalt()
    {
        // leaving blank - I don't need/have a password!
    }


    public function setRoles(array $roles)
    {
        $this->roles = $roles;
    }

    public function getRoles()
    {
        return ['ROLE_USER'];
    }

    public function getPassword(): ?string
    {
        return $this->mdpcitoyen;
    }

    public function getUsername(): ?string
    {
        return $this->prenomcitoyen;
    }


    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
}

demo-dev/templates/base.html.twig
<head>
	<meta charset="UTF-8">
	<title>
		{% block title %}Welcome!
		{% endblock %}
	</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<link rel="stylesheet href=" https://bootswatch.com/4/cerulean/bootstrap.min.css">
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> {% block stylesheets %}{% endblock %}
	</head>
	<body>
		{% block navbar %}
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
				<a class="navbar-brand" href={{path('home')}}>Démocryt</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarColor03">
					<ul class="navbar-nav mr-auto">
						{% block li %}
							<li class="nav-item ">
								<a class="nav-link" href={{path('home')}}>Accueil
									<span class="sr-only">(current)</span>
								</a>
							</li>
							{%if app.user%}
								<li class="nav-item">
									<a class="nav-link" href="#">Créer un groupe</a>
								</li>
								{%else%}
								<li class="nav-item">
									<a class="nav-link" href={{path('inscription_user')}}>Inscription</a>
								</li>
								{%endif%}
							{% endblock %}

						</ul>
						<form class="form-inline my-2 my-lg-0">
							{%if not app.user%}
								<button formaction="{{path('connexion_profil')}}" class="btn btn-secondary mr-sm-2 " type="submit">Connexion</button>
								{%else%}
								<button formaction="{{path('deconnexion_profil')}}" class="btn btn-secondary mr-sm-2 " type="submit">
									<i class="fa fa-sign-out" aria-hidden="true"></i>
								</button>
								<a href="#" class="my-2 my-sm-0" data-toggle="tooltip" title={{app.user.username}}>
									<img class="rounded-circle" style="width : 50px" src="{{asset('imageProfil.jpg')}}" alt="">
								</a>
								{%endif%}
							</form>
						</div>
					</body>
				</body>
			</nav>
		{% endblock %}

		<div class="container justify-content-center">
			{% block body %}
				<h2>
					Salut vous</h2>
			{% endblock %}

		</div>
		{% block javascripts %}
			<script>
				$(document).ready(function () {
$('[data-toggle="tooltip"]').tooltip();
});
			</script>

		{% endblock %}
	</body>
</html>